name = "shorturl"
main = "src/index.ts"
compatibility_date = "2025-01-26"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# CREATE API KEY RANDOMLY
API_KEY = "api-key"

[[d1_databases]]
binding = "DB"
database_name = "database_name"
database_id = "database_id"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1